name: CI test

run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches:
      - 'main'

jobs:
  Test-backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: npm run test
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ This job's status is ${{ job.status }}."
